apiVersion: v1
kind: Pod
metadata:
  name: standalone-nginx
  labels:
    app: nginx
    rel: stable
    ver: "1234"
spec:
  volumes:
    - name: "www"
      emptyDir: {}

    - name: app-settings
      configMap:
        name: app-settings
  
  initContainers:
  - name: content-init
    image: busybox:1.31
    command: ['sh', '-c', 'echo "$(date) - ${MY_NODE_NAME} - ${MY_POD_NAME}" > /content/index.html']
    env:
    - name: "MY_NODE_NAME"
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: "MY_POD_NAME"
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
  
    volumeMounts:
    - name: "www"
      mountPath: "/content"
      readOnly: false

  containers:
  - name: my-nginx-container
    image: nginx:1.18.0-alpine
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    volumeMounts:
      - name: "www"
        mountPath: "/usr/share/nginx/html"
        readOnly: true 
      - name: app-settings
        mountPath: /etc/config
    livenessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 15
      timeoutSeconds: 2
      periodSeconds: 5
      failureThreshold: 1

