apiVersion: batch/v1
kind: Job
metadata:
  name: pie-counter
spec:
  # Specifies the desired number of successfully finished pods the job should run with
  completions: 4
  # Max number of pods the job should run at any given time
  parallelism: 2  
  # how long the job is active for before its terminated
  activeDeadlineSeconds: 240
  # how many number of retries before job is marked as failed
  # backoffLimit: 6 
  template:
    metadata:
      name: pie-counter
    spec:
      # Never restart if container fails, or OnFailure and can set max restarts
      # we can also set max time job is expected to run.
      restartPolicy: Never
      containers:
      - name: pie-counter
        image: alpine
        command:
          - "sh"
          - "-c"
          - "echo /bin/echo Hello from Pod $(hostname) at $(date); sleep 2;"
